import type { Asset, AssetQuery, CreateAssetInput } from '@/types';
import { getDB, getActor, delay, clone, newId, transaction, auditEvent } from './store';
import { access, demandAsset, requireRecord, visibleAsset } from './access';
import { inScope } from '@/utils/permissions';
function get(id:string){return requireRecord(getDB().assets.find(a=>a.id===id||a.assetId===id),'Asset');}
function validate(input:CreateAssetInput){if(!input.name.trim()||!input.serialNumber.trim()||!input.locationId.trim())throw new Error('Name, serial number and location are required.');const category=requireRecord(getDB().categories.find(c=>c.id===input.category&&c.parentId),'Category');if(category.type!==input.type)throw new Error('Category must match the asset type.');requireRecord(getDB().units.find(u=>u.id===input.organisationUnitId&&!u.deletedAt),'Unit');}
export const AssetService={
 async list(query:AssetQuery={}){await delay();access('assets'); /* TODO: replace with axios.get('/api/assets', { params: query }) */
 return clone(getDB().assets.filter(a=>visibleAsset(a)&&(!query.search||[a.name,a.assetId,a.serialNumber].join(' ').toLowerCase().includes(query.search.toLowerCase()))&&(!query.type||a.type===query.type)&&(!query.category||a.category===query.category)&&(!query.status||a.status===query.status)&&(!query.assigneeId||a.currentAssigneeId===query.assigneeId)&&(!query.unitId||a.organisationUnitId===query.unitId)));},
 async getById(id:string){await delay();const a=get(id);demandAsset(a);return clone(a);},
 async categories(query:{type?:string}={}){await delay();access('assets');return clone(getDB().categories.filter(c=>!query.type||c.type===query.type));},
 async create(input:CreateAssetInput){await delay();access('assets','manage');validate(input);const id=newId('A');const asset:Asset={...input,id,assetId:id,status:input.status==='Assigned'?'Available':input.status,currentAssigneeId:null,blockchainStatus:'Unregistered',tokenId:null,createdAt:new Date().toISOString()};demandAsset(asset,'manage');return clone(transaction(()=>{getDB().assets.push(asset);auditEvent('Asset created','Asset',id,{name:asset.name});return asset;}));},
 async update(id:string,input:Partial<CreateAssetInput>){await delay();const a=get(id);demandAsset(a,'manage');const next={...a,...input};validate(next);demandAsset(next,'manage');if(a.currentAssigneeId&&next.organisationUnitId!==a.organisationUnitId)throw new Error('Transfer the asset to change its assigned unit.');if((a.currentAssigneeId&&next.status!=='Assigned')||(!a.currentAssigneeId&&next.status==='Assigned'))throw new Error('Use the assignment or return flow to change ownership.');return clone(transaction(()=>{Object.assign(a,next);auditEvent('Asset updated','Asset',a.id,{name:a.name});return a;}));},
 async assign(id:string,employeeId:string,reason:string,expectedAssigneeId:string|null=null){await delay();const a=get(id);demandAsset(a,'assign');if(a.currentAssigneeId!==expectedAssigneeId)throw new Error('The assignment changed. Refresh this asset and try again.');if(a.status==='In Maintenance')throw new Error('An asset in maintenance cannot be assigned.');if(!reason.trim())throw new Error('A reason is required.');const e=requireRecord(getDB().employees.find(e=>e.id===employeeId&&!e.deletedAt),'Employee');if(e.status!=='Active')throw new Error('Select an active employee.');if(e.id===a.currentAssigneeId)throw new Error('Select a different employee.');
 const {db,user,scope}=access('assets','assign');if(!inScope(scope,user,db.units,e.organisationUnitId,e.id))throw new Error('Access denied. The recipient is outside your team.');
 return clone(transaction(()=>{const previous=a.currentAssigneeId;const time=new Date().toISOString();db.assignments.filter(s=>s.assetId===a.id&&s.status==='Active').forEach(s=>{s.status='Transferred';s.returnedAt=time;});const assignment={id:newId('AS'),assetId:a.id,assigneeId:e.id,assignedById:getActor().id,assignedAt:time,returnedAt:null,reason:reason.trim(),status:'Active' as const,transactionRef:newId('TX-DEMO')};db.assignments.push(assignment);a.currentAssigneeId=e.id;a.organisationUnitId=e.organisationUnitId;a.status='Assigned';auditEvent(previous?'Asset transferred':'Asset assigned','Asset',a.id,{name:a.name,employeeId:e.id,previousEmployeeId:previous||'',transactionRef:assignment.transactionRef,reason});return assignment;}));},
 async return(id:string,expectedAssigneeId:string){await delay();const a=get(id);demandAsset(a,'assign');if(!a.currentAssigneeId||a.currentAssigneeId!==expectedAssigneeId)throw new Error('The assignment changed. Refresh and try again.');return transaction(()=>{const employeeId=a.currentAssigneeId!;getDB().assignments.filter(s=>s.assetId===a.id&&s.status==='Active').forEach(s=>{s.status='Returned';s.returnedAt=new Date().toISOString();});a.currentAssigneeId=null;a.status='Returned';const reference=newId('TX-DEMO');auditEvent('Asset returned','Asset',a.id,{name:a.name,employeeId,transactionRef:reference});return reference;});},
 async history(id:string){await delay();const a=get(id);demandAsset(a);return clone(getDB().assignments.filter(s=>s.assetId===a.id).sort((a,b)=>b.assignedAt.localeCompare(a.assignedAt)));},
 async verify(id:string){await delay();const a=get(id);demandAsset(a,'manage');return clone(transaction(()=>{a.blockchainStatus='Verified';auditEvent('Asset verified','Asset',a.id,{name:a.name,source:'Mock verification'});return a;}));},
};

