import {useState} from 'react';
import {Link} from 'react-router-dom';
import {Upload,CheckCircle2,AlertTriangle,XCircle,Download} from 'lucide-react';
import type {ImportRow,ImportResult} from '@/types';
import {EmployeeImportService} from '@/services/EmployeeImportService';
import {EmployeeService} from '@/services/EmployeeService';
import {useNotifications} from '@/hooks/useNotifications';
import {Panel,Details} from '@/components/ui/Page';
import {Button} from '@/components/ui/Button';
import {Input} from '@/components/ui/Input';
import {Table} from '@/components/ui/Table';
import {Skeleton} from '@/components/ui/Skeleton';
import {Badge} from '@/components/ui/Badge';
const template='name,email,designation,organisationUnitId,managerId,role,status\nAlex Morgan,alex.morgan@acme.example,Frontend Engineer,frontend,E005,employee,Active\n';
export function EmployeeImport(){
 const [step,setStep]=useState(1),[rows,setRows]=useState<ImportRow[]>([]),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<ImportResult|null>(null);const {toast}=useNotifications();
 const valid=rows.filter(r=>!r.errors.length).length,warnings=rows.filter(r=>r.warnings.length&&!r.errors.length).length,invalid=rows.filter(r=>r.errors.length).length;
 async function parse(selected:File){setFile(selected);setError('');setBusy(true);try{setRows(await EmployeeImportService.parse(selected));setStep(2);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div className="stepper">{['Upload file','Review & validate','Confirm import','Import result'].map((title,i)=><span key={title} className={step>=i+1?'active':''}>{i+1}. {title}</span>)}</div><Panel title={['Upload employee data','Review your import','Confirm employee import','Import complete'][step-1]} description="CSV and Excel files · Up to 1,000 rows and 5 MB"><div className="panel-body">{error&&<p className="form-error" role="alert">{error}</p>}
 {step===1&&<><div className="upload-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy&&e.dataTransfer.files[0])void parse(e.dataTransfer.files[0]);}}><Upload size={35}/><h3>Bring your team into Nexus ID</h3><p className="subtle">Drop a file here, or choose one from your computer.</p><Input label="Choose employee file" type="file" accept=".csv,.xlsx" disabled={busy} onChange={e=>{if(e.target.files?.[0])void parse(e.target.files[0]);}}/></div><div className="notice" style={{marginTop:20}}>Required columns: <span className="mono">name, email, designation, organisationUnitId</span>. Optional: employeeId, managerId, role, status, identityStatus. Use existing unit and manager IDs. Missing roles default to Employee and identities to Pending.</div><a className="btn btn-outline" style={{marginTop:18}} download="employee-import-template.csv" href={'data:text/csv;charset=utf-8,'+encodeURIComponent(template)}><Download size={16}/>Download CSV template</a></>}
 {busy&&step===1&&<Skeleton rows={3}/>}
 {step===2&&<><div className="inline wrap" style={{marginBottom:20}}><Badge>{valid+' valid'}</Badge><Badge>{warnings+' warnings'}</Badge><Badge>{invalid+' errors'}</Badge><span className="subtle">{file?.name}</span></div><Table rows={rows.map(r=>({...r,id:String(r.row)}))} caption="Employee import validation" columns={[{key:'row',title:'Row',render:r=>r.row},{key:'validation',title:'Validation',render:r=><span className="inline" title={[...r.errors,...r.warnings].join('\n')}>{r.errors.length?<XCircle size={16} className="error-text"/>:r.warnings.length?<AlertTriangle size={16} color="#fbbf24"/>:<CheckCircle2 size={16} color="#4ade80"/>}{r.errors.length?'Error':r.warnings.length?'Warning':'Valid'}</span>},{key:'name',title:'Name',render:r=>r.values.name},{key:'email',title:'Email',render:r=>r.values.email},{key:'unit',title:'Unit',render:r=>r.values.organisationUnitId},{key:'issues',title:'Validation details',render:r=><span style={{whiteSpace:'normal',minWidth:220,display:'block'}}>{[...r.errors,...r.warnings].join(' · ')||'Ready to import'}</span>}]}/><div className="inline between" style={{marginTop:20}}><Button variant="outline" onClick={()=>{setStep(1);setRows([]);}}>Choose another file</Button><Button disabled={!valid} onClick={()=>setStep(3)}>Continue with {valid} valid rows</Button></div></>}
 {step===3&&<><Details items={[['File',file?.name],['Employees to import',valid],['Rows with warnings',warnings],['Rows to skip',invalid]]}/><div className="notice" style={{marginTop:25}}>Only rows without errors will be imported. Review warnings and confirm the displayed defaults before continuing. Existing employees are not overwritten.</div><div className="inline" style={{marginTop:23}}><Button variant="outline" disabled={busy} onClick={()=>setStep(2)}>Back to preview</Button><Button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const result=await EmployeeService.import(rows);setResult(result);setStep(4);toast(result.imported+' employees imported',result.status==='failed'?'error':result.status==='partial'?'warning':'success');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Importing employees…':'Confirm import'}</Button></div></>}
 {step===4&&result&&<><div className="result-card" role="status"><h3>{result.status==='success'?'Your team is ready':result.status==='partial'?'Import completed with skipped rows':'No employees were imported'}</h3><Details items={[['Result',<Badge>{result.status}</Badge>],['Imported',result.imported],['Skipped',result.skipped]]}/>{result.errors.length>0&&<ul>{result.errors.map((message,i)=><li key={i} className="error-text">{message}</li>)}</ul>}</div><div className="inline wrap" style={{marginTop:22}}><Link to="/employees" className="btn btn-default">View employees</Link><Button variant="outline" onClick={()=>{setStep(1);setRows([]);setResult(null);}}>Import another file</Button></div></>}
 </div></Panel></>;
}

