import {useEffect,useRef,useState} from 'react';
import {Link,useNavigate,useLocation} from 'react-router-dom';
import {Bell,Menu,ChevronDown,CheckCheck,User,Settings,LogOut} from 'lucide-react';
import {Breadcrumbs} from './Breadcrumbs';
import {useSession} from '@/hooks/useSession';
import {useNotifications} from '@/hooks/useNotifications';
import {formatDate,initials} from '@/utils/formatDate';
import {Button} from '@/components/ui/Button';
export function Header({onMenu,menuOpen}:{onMenu:()=>void;menuOpen:boolean}){const {user,logout}=useSession(),{notifications,unreadCount,markRead,markAllRead}=useNotifications();const [panel,setPanel]=useState<'notifications'|'user'|null>(null),ref=useRef<HTMLDivElement>(null),navigate=useNavigate(),location=useLocation();
 useEffect(()=>setPanel(null),[location.pathname]);
 useEffect(()=>{const close=(event:MouseEvent)=>{if(!ref.current?.contains(event.target as Node))setPanel(null);};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setPanel(null);};document.addEventListener('mousedown',close);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('mousedown',close);document.removeEventListener('keydown',escape);};},[]);
 return <header className="workspace-header"><div className="inline"><Button className="mobile-only" variant="ghost" aria-label="Open navigation" aria-expanded={menuOpen} aria-controls="workspace-navigation" onClick={onMenu}><Menu size={21}/></Button><div><Breadcrumbs/><span className="header-title">{location.pathname.split('/')[1]?.replace(/-/g,' ')||'Workspace'}</span></div></div><div className="header-actions" ref={ref}><span className="header-status"><span/> Workspace active</span><Button variant="ghost" className="bell" aria-label={'Notifications, '+unreadCount+' unread'} aria-expanded={panel==='notifications'} onClick={()=>setPanel(panel==='notifications'?null:'notifications')}><Bell size={20}/>{unreadCount>0&&<b>{unreadCount}</b>}</Button><span className="header-divider"/><Button variant="ghost" aria-label="Open user menu" aria-expanded={panel==='user'} onClick={()=>setPanel(panel==='user'?null:'user')}><span className="avatar small">{initials(user?.name||'U')}</span><span className="header-user-name">{user?.name.split(' ')[0]}</span><ChevronDown size={14}/></Button>{panel==='user'&&<div className="dropdown user-dropdown"><Link to={'/employees/'+user?.id}><User size={16}/>My profile</Link><Link to="/settings/account"><Settings size={16}/>Account settings</Link><button type="button" onClick={logout}><LogOut size={16}/>Sign out</button></div>}{panel==='notifications'&&<section className="dropdown notification-dropdown" aria-label="Notifications"><div className="panel-heading"><h2>Notifications</h2><Button variant="ghost" aria-label="Mark all read" onClick={markAllRead}><CheckCheck size={18}/></Button></div>{notifications.length?notifications.map(n=><button key={n.id} type="button" className={'notification-item '+(!n.read?'unread':'')} onClick={()=>{markRead(n.id);navigate(n.link);setPanel(null);}}><strong>{n.title}</strong><span>{n.message}</span><small>{formatDate(n.createdAt,true)}</small></button>):<div className="empty-state"><Bell size={25}/><h3>You’re all caught up</h3><p>Workspace updates will appear here.</p></div>}</section>}</div></header>;
}

