import type {Asset,CreateAssetInput} from '@/types';
import {RecordEditor} from '@/components/ui/RecordEditor';
import {Modal} from '@/components/ui/Modal';
import {QueryState} from '@/components/ui/Page';
import {useReferences} from '@/hooks/useReferences';
import {useSession} from '@/hooks/useSession';
import {useNotifications} from '@/hooks/useNotifications';
import {AssetService} from '@/services/AssetService';
export function AssetEditor({asset,onClose}:{asset?:Asset;onClose:()=>void}){const refs=useReferences(),{user}=useSession(),{toast}=useNotifications();if(!refs.data)return <Modal title="Asset details" onClose={onClose}><QueryState query={refs}>{null}</QueryState></Modal>;
 return <RecordEditor title={asset?'Edit asset':'Register asset'} submitLabel={asset?'Save asset':'Register asset'} onClose={onClose} initial={asset?{name:asset.name,type:asset.type,category:asset.category,serialNumber:asset.serialNumber,condition:asset.condition,locationId:asset.locationId,organisationUnitId:asset.organisationUnitId,subCategory:asset.subCategory,status:asset.status,expiresAt:asset.expiresAt||''}:{type:'Physical',category:'laptops',condition:'Excellent',locationId:'Bengaluru HQ',organisationUnitId:user?.organisationUnitId||'',status:'Available'}} fields={[{key:'name',label:'Asset name',required:true},{key:'type',label:'Asset type',required:true,options:['Physical','Digital'].map(v=>({value:v,label:v}))},{key:'category',label:'Category',required:true,options:refs.data.categories.filter(c=>c.parentId).map(c=>({value:c.id,label:c.type+' · '+c.name})),help:'Select a category that matches the asset type.'},{key:'subCategory',label:'Subcategory / description'},{key:'serialNumber',label:'Serial number',required:true},{key:'condition',label:'Condition',required:true,options:['Excellent','Good','Fair','Needs repair'].map(v=>({value:v,label:v}))},{key:'locationId',label:'Location',required:true},{key:'organisationUnitId',label:'Organisation unit',required:true,disabled:!!asset?.currentAssigneeId,options:refs.data.units.map(u=>({value:u.id,label:u.name}))},{key:'status',label:'Status',required:true,disabled:!!asset?.currentAssigneeId,options:(asset?.currentAssigneeId?['Assigned','Available','In Maintenance','Returned']:['Available','In Maintenance','Returned']).map(v=>({value:v,label:v}))},{key:'expiresAt',label:'Expiry date (optional)',type:'date'}]} onSave={async v=>{const input={...v,subCategory:v.subCategory||'',expiresAt:v.expiresAt||undefined} as CreateAssetInput;if(asset)await AssetService.update(asset.id,input);else await AssetService.create(input);toast(asset?'Asset updated':'Asset registered');}}/>;
}

